CC = c++ #Compiler

CFLAGS = -Wall #Optionen

all: aufgabe05 #Target: all

aufgabe05: aufgabe05.cpp #Target: aufgabe05
	$(CC) $(CFLAGS) -o aufgabe05 aufgabe05.cpp
	
clean : 
	rm aufgabe05 #Target: clean
