CC = c++ #Compiler

CFLAGS = -Wall #Optionen

#all: aufgabe15 aufgabe16

#aufgabe15: aufgabe15.o vektor.o
#	$(CC) -o aufgabe15 aufgabe15.o vektor.o
	
#aufgabe14: aufgabe16.cpp
#	$(CC) $(CFLAGS) -o aufgabe16 aufgabe16.cpp
	
#aufgabe12.o: aufgabe15.cpp vektor.hpp
#	$(CC) $(CFLAGS) -c aufgabe15.cpp
	
#bitmuster.o: vektor.cpp
#	$(CC) $(CFLAGS) -c vektor.cpp
	
clean: 
#	rm aufgabe15
#	rm aufgabe16
	rm *.o
