CC = c++ #Compiler

CFLAGS = -Wall #Optionen

#all: aufgabe17 aufgabe18 aufgabe19

#aufgabe17: aufgabe17.o RandomG.o
#	$(CC) -o aufgabe17 aufgabe17.o RandomG.o

#aufgabe18: aufgabe18.o RandomG.o
#	$(CC) -o aufgabe18 aufgabe18.o RandomG.o

#aufgabe19: aufgabe19.o RandomG.o
#	$(CC) -o aufgabe19 aufgabe19.o RandomG.o


#aufgabe17.o: aufgabe17.cpp RandomG.hpp
#	$(CC) $(CFLAGS) -c aufgabe17.cpp
	
#aufgabe18.o: aufgabe18.cpp RandomG.hpp
#	$(CC) $(CFLAGS) -c aufgabe18.cpp
	
#aufgabe19.o: aufgabe19.cpp RandomG.hpp
#	$(CC) $(CFLAGS) -c aufgabe19.cpp

	
#RandomG.o: RandomG.cpp RandomG.hpp
#	$(CC) $(CFLAGS) -c RandomG.cpp
	
clean: 
#	rm aufgabe17
	rm *.o
