CC = c++ #Compiler

CFLAGS = -Wall #Optionen

all: aufgabe23

aufgabe23: aufgabe23.cpp
	$(CC) -o aufgabe23 aufgabe23.cpp
	
#aufgabe21: aufgabe21.o Zufallsgenerator.o 
#	$(CC) -o aufgabe21 aufgabe21.o Zufallsgenerator.o
	
#aufgabe21.o: aufgabe21.cpp Zufallsgenerator.hpp
#	$(CC) $(CFLAGS) -c aufgabe21.cpp

#Zufallsgenerator.o: Zufallsgenerator.cpp Zufallsgenerator.hpp
#	$(CC) $(CFLAGS) -c Zufallsgenerator.cpp
	
clean: 
	rm aufgabe23
	#rm aufgabe21
	#rm *o

	
