CC = c++ #Compiler

CFLAGS = -Wall #Optionen

all: aufgabe20 aufgabe21

aufgabe20: aufgabe20.cpp
	$(CC) -o aufgabe20 aufgabe20.cpp
	
aufgabe21: aufgabe21.cpp
	$(CC) -o aufgabe21 aufgabe21.cpp
	
clean: 
	rm aufgabe20
	rm aufgabe21

	
